version: 2.1
jobs:
  build:
    shell: /bin/bash --login -eo pipefail

    macos:
      xcode: '11.5.0'

    steps:
    - checkout

    - run: 
        name: Make Output Directory
        command: mkdir -p 'artifacts'

    - run:
        name: Install Carthage
        command: |
          brew update
          brew install carthage

    - run:
        name: Build hello-tvos
        command: xcodebuild build -scheme 'hello-tvos' CODE_SIGNING_ALLOWED=NO | tee 'artifacts/xcode_build_raw.log' | xcpretty

    - store_artifacts:
        path: artifacts
